ci: attempt to run on macOS with 5.5 toolchain

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -77,8 +77,9 @@ jobs:
         run: curl -O https://swift.org/builds/swift-5.5-branch/xcode/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-04-19-a/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-04-19-a-osx.pkg
       - name: Install Swift 5.5 Toolchain
         run: sudo installer -pkg swift-5.5-DEVELOPMENT-SNAPSHOT-2021-04-19-a-osx.pkg -target /
-      - name: Build
-        run: /Library/Developer/Toolchains/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-04-19-a.xctoolchain/usr/bin/swift build
+      - name: Build Tests
+        # note that we permit test failures because all we are doing is building the .xctest module so we can manually run it with the correct DYLD_LIBRARY_PATH
+        run: /Library/Developer/Toolchains/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-04-19-a.xctoolchain/usr/bin/swift-test || echo "Tolerating test failure"
       - name: Test
         run: DYLD_LIBRARY_PATH=/Library/Developer/Toolchains/swift-5.5-DEVELOPMENT-SNAPSHOT-2021-04-19-a.xctoolchain/usr/lib/swift/macosx/ /Applications/Xcode.app/Contents/Developer/usr/bin/xctest /opt/src/github/marcprux/SwiftAsyncAwaitDemo/.build/x86_64-apple-macosx/debug/SwiftAsyncAwaitDemoPackageTests.xctest
 
